steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
    'build',
    '-t',
    'europe-central2-docker.pkg.dev/sleepr-413909/reservations/production',
    '-f',
    'apps/reservations/Dockerfile',
    '.'
  ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'europe-central2-docker.pkg.dev/sleepr-413909/reservations/production' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
    'build',
    '-t',
    'europe-central2-docker.pkg.dev/sleepr-413909/auth/production',
    '-f',
    'apps/auth/Dockerfile',
    '.'
  ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'europe-central2-docker.pkg.dev/sleepr-413909/auth/production' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
    'build',
    '-t',
    'europe-central2-docker.pkg.dev/sleepr-413909/payments/production',
    '-f',
    'apps/payments/Dockerfile',
    '.'
  ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'europe-central2-docker.pkg.dev/sleepr-413909/payments/production' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
    'build',
    '-t',
    'europe-central2-docker.pkg.dev/sleepr-413909/notifications/production',
    '-f',
    'apps/notifications/Dockerfile',
    '.'
  ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'europe-central2-docker.pkg.dev/sleepr-413909/notifications/production' ]