services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: europe-central2-docker.pkg.dev/sleepr-413909/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: europe-central2-docker.pkg.dev/sleepr-413909/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: europe-central2-docker.pkg.dev/sleepr-413909/payments/production
    ports:
      - '3003:3003'
    env_file:
      - ../apps/payments/.env
  notifications:
    image: europe-central2-docker.pkg.dev/sleepr-413909/notifications/production
    ports:
      - '3004:3004'
    env_file:
      - ../apps/notifications/.env
  mongo:
    image: mongo